injectWorkspacePackages: true

packages:
  - "todoapp-vscode-plugin"
  - "honoapp-vscode-plugin"
  - "honoapp"
  - "reactapp"
  - "preloads/*"
  - "../extends-vite"
  - "../extends-ssh"
  - "../extends-antd"
  - "../extends-zustand"
  - "../extends-hono"
